#import <Foundation/Foundation.h>
#import "SWGError.h"
#import "SWGApi.h"

/**
* Switch Database REST API
* Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
*
* OpenAPI spec version: 1.2.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGAuthorizationApi: NSObject <SWGApi>

extern NSString* kSWGAuthorizationApiErrorDomain;
extern NSInteger kSWGAuthorizationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Generate Access Token
/// For generating Access Token, you need API Key and API Secret parameters that are provided from the developer portal. At the request, API Key that will be sent by using header is generated as portal API Key and Signature parameter is generated as md5(APISecret + ExpireTimestamp) format. At Expire parameter, token's expire date and time information must be proper to ISO 8601 standarts and Unix Time format with msec information. 
///
/// @param aPIKey Your Switch API Key.
/// @param signature Signature parameter is generated as md5(APISecret + ExpireTimestamp) format.
/// @param expire Expire parameter, token&#39;s expire date and time information must be proper to ISO 8601 standarts and Unix Time format with msec information.
/// 
///  code:200 message:"Access Token String",
///  code:401 message:"Unauthorized (Given AccessToken parameter is invalid.)",
///  code:403 message:"Security Exception (Unsecured request.)",
///  code:404 message:"Method Not Found (Called API could not found.)",
///  code:429 message:"TooManyRequests (API limit excess. The remaning time to the date-time for that API can answer the requests is calculated as Unix Time format under TheNextReset.)",
///  code:500 message:"ServiceException (Unexpected Error There is a detailed explanation under ErrorMessage.)"
///
/// @return NSString*
-(NSURLSessionTask*) tokenGetWithAPIKey: (NSString*) aPIKey
    signature: (NSString*) signature
    expire: (NSNumber*) expire
    completionHandler: (void (^)(NSString* output, NSError* error)) handler;



@end
